spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-instance
        service-name: ${spring.application.name}
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

secure:
  ignored:
    urls:
      - /product/**
      - /actuator/**
      - /adress/**
      - /user/**
      - /order/**
      - /stock/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: yukismimi #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)
  tokenHead: Yuki  #JWT负载中拿到开头