server:
  port: 9030
spring:
  #  cloud:
  #    consul:
  #      host: localhost
  #      port: 8500
  #      discovery:
  #        instance-id: stock-service-instance
  #        service-name: ${spring.application.name}
  application:
    name: stock-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#custom-filter:
#  urls:
#    - /stock/*