server:
  port: 9020
spring:
  #  cloud:
  #    consul:
  #      host: localhost
  #      port: 8500
  #      discovery:
  #        instance-id: transaction-service-instance
  #        service-name: ${spring.application.name}
  application:
    name: order-service
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456
    virtual-host: mall
    publisher-returns: true
  jpa:
    show-sql: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#custom-filter:
#  urls:
#    - /order/add