server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yukismimi/cloud.git
#          username:
#          password:
          search-paths: config-repo
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: config-server
        service-name: ${spring.application.name}
  application:
    name: config-server

